name: Build Ruffle WASM

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-wasm:
    name: Build Ruffle WASM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # wasm-bindgen-cli 版本必须匹配 wasm-bindgen crate 版本
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli --version 0.2.93

      - name: Install wasm-opt
        uses: sigoden/install-binary@v1
        with:
          repo: WebAssembly/binaryen
          tag: version_119
          name: wasm-opt

      - name: Install node packages
        working-directory: web
        run: npm ci

      - name: Build WASM
        env:
          CARGO_FEATURES: jpegxr
          WASM_SOURCE: cargo_and_store
        working-directory: web
        run: npm run build:repro

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ruffle-wasm
          path: web/packages/*
          if-no-files-found: error
